# .streamlit/secrets.toml

#Don't use this for deployment, use remote server instead
[connections.mysql]
dialect = "mysql"
host = "localhost"
port = 3306
database = "sample"
username = "root"
password = "1234"
