# .streamlit/secrets.toml

[connections.mysql]
dialect = "mysql"
host = "mysql-13574bf9-student122020-9ea3.a.aivencloud.com"
port = 25957
database = "defaultdb"
username = "avnadmin"
password = ************
